### ISSUE TITLE
Run time error (std::logic_error)

### ISSUE THREAD

**Issue by gledr** [pablo-aledo/forest_v2.0#2]
When executing forest the following happens:
```bash
���  forest
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
[1]    5565 abort (core dumped)  forest
```

By debugging the problem using gdb the following information can be obtained:
```bash
Program received signal SIGABRT, Aborted.
0x00007ffff6f638a0 in raise () from /usr/lib/libc.so.6
(gdb) where
#0  0x00007ffff6f638a0 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6f64f09 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff78d7d77 in __gnu_cxx::__verbose_terminate_handler () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff78d58e6 in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff78d5933 in std::terminate () at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff78d5b88 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x555555802840, tinfo=0x7ffff7bc3098 <typeinfo for std::logic_error>, dest=0x7ffff78eb4c0 <std::logic_error::~logic_error()>) at /build/gcc-multilib/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:93
#6  0x00007ffff79000a3 in std::__throw_logic_error (__s=__s@entry=0x7ffff7986ba0 "basic_string::_M_construct null not valid") at /build/gcc-multilib/src/gcc/libstdc++-v3/src/c++11/functexcept.cc:66
#7  0x00007ffff79706e4 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (this=this@entry=0x7fffffffdda0, __beg=0x0, __end=<optimized out>)
    at /build/gcc-multilib/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:212
#8  0x00007ffff7970861 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char const*> (__end=<optimized out>, __beg=<optimized out>, this=0x7fffffffdda0)
    at /build/gcc-multilib/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:220
#9  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (__end=<optimized out>, __beg=<optimized out>, this=0x7fffffffdda0)
    at /build/gcc-multilib/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:239
#10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffdda0, __s=<optimized out>, __a=...) at /build/gcc-multilib/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:495
#11 0x0000555555566dbf in load_default_options () at cmd_options.cpp:214
#12 0x0000555555558ae8 in main (argc=1, argv=0x7fffffffdf58) at forest.cpp:48
```
Where cmd_options.cpp:214 refers to the following code block:
```c++
if(string(getenv("FOREST_HOME")) != "")
		set_option("base_path", string(getenv("FOREST_HOME")));
```

The Problem here is that  regarding to the man page of getenv:
```man
The getenv() function returns a pointer to the value in the environment, or NULL if there is no match.
```

A NULL pointer gets returned when there is no entry for the environment variable.

This means the constructor of std::string gets called using a Null pointer as argument.
A possible fix would be:
```c++
if(getenv("FOREST_HOME") != 0)
		set_option("base_path", string(getenv("FOREST_HOME")));
```

The mentioned problem will be observable at all instructions from 214-221
```c++
if(string(getenv("FOREST_HOME")) != "")
	set_option("base_path", string(getenv("FOREST_HOME")));
if(string(getenv("LLVM_HOME")) != "")
	set_option("llvm_path", string(getenv("LLVM_HOME")));
if(string(getenv("CPACHECKER_HOME")) != "")
	set_option("cpachecker_path", string(getenv("CPACHECKER_HOME")));
if(string(getenv("CSEQ_HOME")) != "")
	set_option("cseq_path", string(getenv("CSEQ_HOME")));
```

**Comment by Ryroro** [comment]
Try to echo "FOREST_HOME" and "LLVM_HOME" to see if the path has been exported. This error is caused by the null reference to the env variable. Export the path again and it should be fine.
